AWSTemplateFormatVersion: '2010-09-09'
Description: Demo CloudFormation template for GitHub Actions CI/CD.

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment stage for naming.

Resources:
  DemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "tk-github-actions-demo-bucket-${AWS::AccountId}-${EnvironmentName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  BucketArn:
    Description: The ARN of the S3 Bucket
    Value: !GetAtt DemoBucket.Arn
